//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Subject()
        {
            this.tbl_Exam = new HashSet<tbl_Exam>();
        }

        [Key] 
        public int Subject_Id { get; set; }
        [Required(ErrorMessage ="*Subject Name is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Subject_Name { get; set; }
        [Required(ErrorMessage = "*Subject Code is Requird")]
        [RegularExpression(@"^[0-9]{9,9}$", ErrorMessage = "Must be 9 Number only")]
        public string Subject_Code { get; set; }
        public System.DateTime Subject_CreatedOn { get; set; }
        [Required(ErrorMessage = "*Level is Requird")]
        public int Level_Id { get; set; }
        [Required(ErrorMessage = "*Department is Requird")]
        public int Department_Id { get; set; }
        public int Teacher_Id { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Exam> tbl_Exam { get; set; }
        public virtual tbl_Level tbl_Level { get; set; }
        public virtual tbl_Teacher tbl_Teacher { get; set; }
    }
}
