//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Student()
        {
            this.tbl_Result = new HashSet<tbl_Result>();
        }
        [Key]
        public int Student_Id { get; set; }
        [Required(ErrorMessage = "*Student Name is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Student_Name { get; set; }
        [Required(ErrorMessage = "*Student Email is Requird")]
        [DataType(DataType.EmailAddress)]
        public string Student_Email { get; set; }
        [Required(ErrorMessage = "*Student Password is Requird")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^\da-zA-Z])(.{8,30})$", ErrorMessage = "*Should Be strong and 8 TO 32 Char")]
        [DataType(DataType.Password)]
        public string Student_Password { get; set; }
        [Required(ErrorMessage = "*Student Phone is Requird")]
        [RegularExpression(@"^[0-9]{11,11}$", ErrorMessage = "Number only and 11")]
        public string Student_Phone { get; set; }
        public System.DateTime Student_CreatedOn { get; set; }
        public int Level_Id { get; set; }
        public int Department_Id { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tbl_Level tbl_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Result> tbl_Result { get; set; }
    }
}
