//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Announcement
    {
        [Key]
        public int Announcement_Id { get; set; }
        [Required(ErrorMessage = "*Announcement Title is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Announcement_Title { get; set; }
        [Required(ErrorMessage = "*Announcement Dtails is Requird")]
        [MaxLength(240, ErrorMessage = "*Should be Less Than 240 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Announcement_Details { get; set; }
        public System.DateTime Announcement_CreatedOn { get; set; }
        public int Teacher_Id { get; set; }
        [Required(ErrorMessage = "*Level is Requird")]
        public int Level_Id { get; set; }
        [Required(ErrorMessage = "*Department is Requird")]

        public int Department_Id { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tbl_Level tbl_Level { get; set; }
        public virtual tbl_Teacher tbl_Teacher { get; set; }
    }
}
