//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Teacher()
        {
            this.tbl_Announcement = new HashSet<tbl_Announcement>();
            this.tbl_Exam = new HashSet<tbl_Exam>();
            this.tbl_QuestionMCQ = new HashSet<tbl_QuestionMCQ>();
            this.tbl_QuestionTrueFalse = new HashSet<tbl_QuestionTrueFalse>();
            this.tbl_Subject = new HashSet<tbl_Subject>();
        }
        [Key]
        public int Teacher_Id { get; set; }
        [Required(ErrorMessage = "*Teacher Name is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Teacher_Name { get; set; }
        [Required(ErrorMessage = "*Teacher Email is Requird")]
        [DataType(DataType.EmailAddress)]
        public string Teacher_Email { get; set; }
        [Required(ErrorMessage = "*Teacher Password is Requird")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^\da-zA-Z])(.{8,30})$", ErrorMessage = "*Should Be strong and 8 TO 32 Char")]
        [DataType(DataType.Password)]
        public string Teacher_Password { get; set; }
        [Required(ErrorMessage = "*Teacher Phone is Requird")]
        [RegularExpression(@"^[0-9]{11,11}$", ErrorMessage = "Number only and 11")]
        public string Teacher_Phone { get; set; }
        public System.DateTime Teacher_CreatedOn { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Announcement> tbl_Announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Exam> tbl_Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuestionMCQ> tbl_QuestionMCQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuestionTrueFalse> tbl_QuestionTrueFalse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Subject> tbl_Subject { get; set; }
    }
}
