//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Admin
    {   [Key]
        public int Admin_Id { get; set; }
        [Required(ErrorMessage = "*Admin Name is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Admin_Name { get; set; }
        [Required(ErrorMessage = "*Admin Email is Requird")]
        [DataType(DataType.EmailAddress)]
        public string Admin_Email { get; set; }
        [Required(ErrorMessage = "*Admin Password is Requird")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^\da-zA-Z])(.{8,30})$", ErrorMessage = "*Should Be strong and 8 TO 32 Char")]
        [DataType(DataType.Password)]
        public string Admin_Password { get; set; }
        [Required(ErrorMessage = "*Admin Phone is Requird")]
        [RegularExpression(@"^[0-9]{11,11}$", ErrorMessage = "Number only and 11")]
        public string Admin_Phone { get; set; }
        public System.DateTime Admin_CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
    }
}
