//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_QuestionTrueFalse
    {
        [Key]
        public int QuestionTrueFalse_Id { get; set; }
        [Required(ErrorMessage = "Question Text is Required")]
        [MaxLength(240, ErrorMessage = "Should Be less Than 240 Letters")]
        [MinLength(5, ErrorMessage = "Should Be More Than 240 Letters")]
        public string QuestionTrueFalse_text { get; set; }
        public string QuestionTrueFalse_OptionA { get; set; }
        public string QuestionTrueFalse_OptionB { get; set; }
        [Required(ErrorMessage = "Correct Answer is Required")]
        public string QuestionTrueFalse_CorrectAnswer { get; set; }
        [Required(ErrorMessage = "Mark is Required")]
        [RegularExpression(@"^[0-9]{1,2}$", ErrorMessage = "Number only")]
        [Range(1, 10, ErrorMessage = "Should Be from 1 To 10")]
        public int QuestionTrueFalse_Mark { get; set; }
        public int Teacher_Id { get; set; }
        [Required(ErrorMessage = "Eaxm is Required")]
        public int Exam_Id { get; set; }
    
        public virtual tbl_Exam tbl_Exam { get; set; }
        public virtual tbl_Teacher tbl_Teacher { get; set; }
    }
}
