//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Level()
        {
            this.tbl_Announcement = new HashSet<tbl_Announcement>();
            this.tbl_Student = new HashSet<tbl_Student>();
            this.tbl_Subject = new HashSet<tbl_Subject>();
        }
        [Key]
        public int Level_Id { get; set; }
        [Required(ErrorMessage = "*Level Name is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Level_Name { get; set; }
        [Required(ErrorMessage = "*Subject Code is Requird")]
        [RegularExpression(@"^[0-9]{9,9}$", ErrorMessage = "Must be 9 Number only")]
        public string Level_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Announcement> tbl_Announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Student> tbl_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Subject> tbl_Subject { get; set; }
    }
}
