//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemExamWebSite.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Exam()
        {
            this.tbl_QuestionMCQ = new HashSet<tbl_QuestionMCQ>();
            this.tbl_QuestionTrueFalse = new HashSet<tbl_QuestionTrueFalse>();
            this.tbl_Result = new HashSet<tbl_Result>();
        }
        [Key]
    
        public int Exam_Id { get; set; }
        [Required(ErrorMessage = "*Exam Name is Requird")]
        [MaxLength(40, ErrorMessage = "*Should be Less Than 40 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Exam_Name { get; set; }
        [Required(ErrorMessage = "*Exam Instruction is Requird")]
        [MaxLength(140, ErrorMessage = "*Should be Less Than 140 Letters")]
        [MinLength(5, ErrorMessage = "*Should Be More Than 5 Letters")]
        public string Exam_Instruction { get; set; }
        [Required(ErrorMessage = "*Exam Munite Duration is Requird")]
        [RegularExpression(@"^[0-9]{1,2}$", ErrorMessage = "Number only")]
        public int Exam_MuniteDuration { get; set; }
        [Required(ErrorMessage = "*Total Mark is Requird")]
        [RegularExpression(@"^[0-9]{1,2}$", ErrorMessage = "Number only")]
        public int Exam_TotalMark { get; set; }
        [Required(ErrorMessage = "*Exam Start On is Requird")]
        public System.DateTime Exam_StartOn { get; set; }
        [Required(ErrorMessage = "*Exam End On is Requird")]
        public System.DateTime Exam_EndOn { get; set; }
        [Required(ErrorMessage = "*Passing Mark is Requird")]
        [RegularExpression(@"^[0-9]{1,2}$", ErrorMessage = "Number only")]
        public int Exam_PassingMark { get; set; }
        public int Teacher_Id { get; set; }
        [Required(ErrorMessage = "*Subject On is Requird")]
        public int Subject_Id { get; set; }
        public System.DateTime Exam_CreatedOn { get; set; }
    
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_Teacher tbl_Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuestionMCQ> tbl_QuestionMCQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuestionTrueFalse> tbl_QuestionTrueFalse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Result> tbl_Result { get; set; }
    }
}
